CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(150) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(150),
  "role" varchar(20) NOT NULL DEFAULT 'student',
  "student_code" varchar(20) UNIQUE,
  "class_id" integer,
  "faculty_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "faculties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(10) UNIQUE NOT NULL,
  "name" varchar(150) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "classes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "faculty_id" integer NOT NULL,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(150) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "name" varchar(128) NOT NULL,
  "parent_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "name" varchar(128) NOT NULL,
  "color" varchar(7),
  "parent_id" integer
);

CREATE TABLE "workspaces" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(20) NOT NULL,
  "name" varchar(150) NOT NULL,
  "description" text,
  "owner_id" integer NOT NULL,
  "ref_class_id" integer,
  "ref_faculty_id" integer,
  "default_member_permission" varchar(10) DEFAULT 'view',
  "is_deleted" boolean DEFAULT false,
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "workspace_members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspace_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "permission_level" varchar(10) NOT NULL DEFAULT 'view',
  "joined_at" timestamp DEFAULT (now())
);

CREATE TABLE "workspace_invitations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspace_id" integer NOT NULL,
  "invited_user_id" integer NOT NULL,
  "invited_by" integer NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "responded_at" timestamp
);

CREATE TABLE "documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer NOT NULL,
  "workspace_id" integer,
  "category_id" integer,
  "source_document_id" integer,
  "title" varchar(255) NOT NULL,
  "description" text,
  "file_path" varchar(1024) NOT NULL,
  "file_type" varchar(50),
  "file_size" bigint,
  "checksum" varchar(64) NOT NULL,
  "content" text,
  "metadata" jsonb,
  "search_vector" tsvector,
  "is_important" boolean DEFAULT false,
  "is_deleted" boolean DEFAULT false,
  "deleted_at" timestamp,
  "trash_batch_id" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "document_tags" (
  "document_id" integer,
  "tag_id" integer,
  PRIMARY KEY ("document_id", "tag_id")
);

CREATE TABLE "document_versions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "version_no" integer NOT NULL,
  "file_path" varchar(1024) NOT NULL,
  "checksum" varchar(64),
  "uploaded_by" integer,
  "note" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "note" text NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "trash_batches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspace_id" integer,
  "name" varchar(255) NOT NULL,
  "deleted_by" integer NOT NULL,
  "deleted_at" timestamp DEFAULT (now()),
  "purge_at" timestamp NOT NULL
);

CREATE TABLE "document_shares" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "source_document_id" integer NOT NULL,
  "from_user_id" integer NOT NULL,
  "to_user_id" integer NOT NULL,
  "share_type" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "type" varchar(30) NOT NULL,
  "workspace_id" integer,
  "document_id" integer,
  "message" varchar(255) NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "favorites" (
  "user_id" integer,
  "document_id" integer,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "document_id")
);

CREATE TABLE "download_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "action" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "processing_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "job_type" varchar(50) NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "result" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "finished_at" timestamp
);

CREATE UNIQUE INDEX ON "workspace_members" ("workspace_id", "user_id");

CREATE INDEX ON "documents" ("checksum");

CREATE INDEX ON "documents" USING GIN ("search_vector");

ALTER TABLE "users" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculties" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "classes" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculties" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tags" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tags" ADD FOREIGN KEY ("parent_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspaces" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspaces" ADD FOREIGN KEY ("ref_class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspaces" ADD FOREIGN KEY ("ref_faculty_id") REFERENCES "faculties" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspace_members" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspace_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspace_invitations" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspace_invitations" ADD FOREIGN KEY ("invited_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "workspace_invitations" ADD FOREIGN KEY ("invited_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("source_document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("trash_batch_id") REFERENCES "trash_batches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_versions" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_versions" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notes" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trash_batches" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trash_batches" ADD FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_shares" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_shares" ADD FOREIGN KEY ("source_document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_shares" ADD FOREIGN KEY ("from_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_shares" ADD FOREIGN KEY ("to_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "download_logs" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "download_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "processing_jobs" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
