"""fix missing columns across multiple tables

Revision ID: 5cf3f5391595
Revises: 93f46eb359df
Create Date: 2026-09-26 12:18:18.399376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf3f5391595'
down_revision: Union[str, Sequence[str], None] = '93f46eb359df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_tags',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'tag_id')
    )
    op.create_table('community_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('published_document_id', sa.Integer(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='check_document_ratings_stars_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_ratings_document_user')
    )
    op.add_column('documents', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('thumbnail_path', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('is_orphaned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('orphaned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('trash_source', sa.String(length=30), nullable=True))
    op.add_column('documents', sa.Column('trash_group_name', sa.String(length=150), nullable=True))
    op.add_column('documents', sa.Column('is_bundle', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('bundle_parent_id', sa.Integer(), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('documents', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_bundle_parent_id'), 'documents', ['bundle_parent_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'documents', ['bundle_parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'subjects', ['subject_id'], ['id'])
    op.alter_column('folders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_folders_workspace_id', 'folders', ['workspace_id'], unique=False)
    op.add_column('tags', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'updated_at')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'workspace_id')
    op.drop_index('ix_folders_workspace_id', table_name='folders')
    op.alter_column('folders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_bundle_parent_id'), table_name='documents')
    op.alter_column('documents', 'checksum',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('documents', 'bundle_parent_id')
    op.drop_column('documents', 'is_bundle')
    op.drop_column('documents', 'trash_group_name')
    op.drop_column('documents', 'trash_source')
    op.drop_column('documents', 'orphaned_at')
    op.drop_column('documents', 'is_orphaned')
    op.drop_column('documents', 'thumbnail_path')
    op.drop_column('documents', 'is_public')
    op.drop_column('documents', 'subject_id')
    op.drop_table('document_ratings')
    op.drop_table('community_submissions')
    op.drop_table('folder_tags')
    op.drop_table('subjects')
    # ### end Alembic commands ###
