"""Add workspace_tags table

Revision ID: 93f46eb359df
Revises: f844331e6c1e
Create Date: 2026-09-05 15:08:21.672847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93f46eb359df'
down_revision: Union[str, Sequence[str], None] = 'f844331e6c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tag_id', name='uq_workspace_tag')
    )
    op.create_index('ix_owner_user_id', 'workspace_tags', ['owner_user_id'], unique=False)
    op.create_index('ix_tag_id', 'workspace_tags', ['tag_id'], unique=False)
    op.create_index('ix_workspace_id', 'workspace_tags', ['workspace_id'], unique=False)
    op.alter_column('trash_batches', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('trash_batches', 'purge_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('trash_batches_deleted_by_fkey'), 'trash_batches', type_='foreignkey')
    op.drop_constraint(op.f('trash_batches_workspace_id_fkey'), 'trash_batches', type_='foreignkey')
    op.create_foreign_key(None, 'trash_batches', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trash_batches', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('workspace_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('workspace_invitations', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_workspace_invitations_invited_user', 'workspace_invitations', ['invited_user_id', 'status'], unique=False)
    op.drop_constraint(op.f('workspace_invitations_invited_by_fkey'), 'workspace_invitations', type_='foreignkey')
    op.drop_constraint(op.f('workspace_invitations_invited_user_id_fkey'), 'workspace_invitations', type_='foreignkey')
    op.drop_constraint(op.f('workspace_invitations_workspace_id_fkey'), 'workspace_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_invitations', 'users', ['invited_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_invitations', 'users', ['invited_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_invitations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    
    # --------------------------------------------------------------------------
    # KHẮC PHỤC LỖI NOT NULL CHO WORKSPACE_MEMBERS.JOINED_AT
    # --------------------------------------------------------------------------
    # Bước 1: Cập nhật các dòng có joined_at đang bị NULL thành thời gian hiện tại
    op.execute("UPDATE workspace_members SET joined_at = NOW() WHERE joined_at IS NULL")

    # Bước 2: Thiết lập joined_at sang DateTime(timezone=True) và ép NOT NULL + Server Default
    op.alter_column('workspace_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('NOW()'),
               nullable=False)
    # --------------------------------------------------------------------------

    op.drop_constraint(op.f('uq_workspace_user'), 'workspace_members', type_='unique')
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False)
    op.drop_constraint(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workspace_members', 'id')
    op.alter_column('workspaces', 'default_member_permission',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('workspaces', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('workspaces', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('workspaces_owner_id_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_owner_id_fkey'), 'workspaces', 'users', ['owner_id'], ['id'])
    op.alter_column('workspaces', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('workspaces', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workspaces', 'default_member_permission',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.add_column('workspace_members', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('workspace_members', 'joined_at', nullable=True)
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members')
    op.create_unique_constraint(op.f('uq_workspace_user'), 'workspace_members', ['workspace_id', 'user_id'])
    op.alter_column('workspace_members', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.drop_constraint(None, 'workspace_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_invitations_workspace_id_fkey'), 'workspace_invitations', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('workspace_invitations_invited_user_id_fkey'), 'workspace_invitations', 'users', ['invited_user_id'], ['id'])
    op.create_foreign_key(op.f('workspace_invitations_invited_by_fkey'), 'workspace_invitations', 'users', ['invited_by'], ['id'])
    op.drop_index('ix_workspace_invitations_invited_user', table_name='workspace_invitations')
    op.alter_column('workspace_invitations', 'responded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('workspace_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'trash_batches', type_='foreignkey')
    op.drop_constraint(None, 'trash_batches', type_='foreignkey')
    op.create_foreign_key(op.f('trash_batches_workspace_id_fkey'), 'trash_batches', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('trash_batches_deleted_by_fkey'), 'trash_batches', 'users', ['deleted_by'], ['id'])
    op.alter_column('trash_batches', 'purge_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('trash_batches', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_workspace_id', table_name='workspace_tags')
    op.drop_index('ix_tag_id', table_name='workspace_tags')
    op.drop_index('ix_owner_user_id', table_name='workspace_tags')
    op.drop_table('workspace_tags')
    # ### end Alembic commands ###