"""add is_dissolving and dissolve_at to workspace

Revision ID: f844331e6c1e
Revises: dae4972dff87
Create Date: 2026-09-03 16:13:07.251922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f844331e6c1e'
down_revision: Union[str, Sequence[str], None] = 'dae4972dff87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('folders_owner_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'users', ['owner_id'], ['id'])
    op.drop_column('folders', 'updated_at')
    op.add_column('workspace_invitations', sa.Column('message', sa.String(length=500), nullable=True))
    
    # Sửa dòng này: Thêm server_default để điền giá trị false cho các dòng dữ liệu cũ
    op.add_column('workspaces', sa.Column('is_dissolving', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    op.add_column('workspaces', sa.Column('dissolve_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'dissolve_at')
    op.drop_column('workspaces', 'is_dissolving')
    op.drop_column('workspace_invitations', 'message')
    op.add_column('folders', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key(op.f('folders_owner_id_fkey'), 'folders', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('folders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###