CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(150) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(150),
  "role" varchar(20) DEFAULT 'personal',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "name" varchar(128) NOT NULL,
  "parent_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "name" varchar(128) NOT NULL,
  "color" varchar(7),
  "parent_id" integer
);

CREATE TABLE "documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer NOT NULL,
  "category_id" integer,
  "title" varchar(255) NOT NULL,
  "description" text,
  "file_path" varchar(1024) NOT NULL,
  "file_type" varchar(50),
  "file_size" bigint,
  "checksum" varchar(64) NOT NULL,
  "content" text,
  "metadata" jsonb,
  "search_vector" tsvector,
  "is_important" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "document_tags" (
  "document_id" integer,
  "tag_id" integer,
  PRIMARY KEY ("document_id", "tag_id")
);

CREATE TABLE "document_versions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "version_no" integer NOT NULL,
  "file_path" varchar(1024) NOT NULL,
  "checksum" varchar(64),
  "uploaded_by" integer,
  "note" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "note" text NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "favorites" (
  "user_id" integer,
  "document_id" integer,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "document_id")
);

CREATE TABLE "download_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "action" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "processing_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "job_type" varchar(50) NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "result" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "finished_at" timestamp
);

CREATE INDEX ON "documents" ("checksum");

CREATE INDEX ON "documents" USING GIN ("search_vector");

ALTER TABLE "categories" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tags" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tags" ADD FOREIGN KEY ("parent_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_versions" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_versions" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notes" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "download_logs" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "download_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "processing_jobs" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
